INSERT INTO sss_sistemas VALUES('APR','Apertura');
INSERT INTO sss_sistemas VALUES('CFG','Configuración');
INSERT INTO sss_sistemas VALUES('CIE','Cierre');
INSERT INTO sss_sistemas VALUES('CXP','Cuentas por Pagar');
INSERT INTO sss_sistemas VALUES('INS','Instala');
INSERT INTO sss_sistemas VALUES('MIS','Módulo Integrador Sigesp');
INSERT INTO sss_sistemas VALUES('RPC','Sistema de Registro de Contratista/Proveedores y Beneficiario');
INSERT INTO sss_sistemas VALUES('SAF','Sistema de Activos Fijos');
INSERT INTO sss_sistemas VALUES('SCB','Sistema de Banco');
INSERT INTO sss_sistemas VALUES('SCF','Sistema de Contabilidad Fiscal');
INSERT INTO sss_sistemas VALUES('SCG','Sistema de Contabilidad General');
INSERT INTO sss_sistemas VALUES('SCV','Sistema de Control de Viáticos');
INSERT INTO sss_sistemas VALUES('SEP','Sistema de Ejecución Presupuestaria');
INSERT INTO sss_sistemas VALUES('SFC','Sistema de Facturacion y Cobranza');
INSERT INTO sss_sistemas VALUES('SFI','Sistemas Integrados - Facturación');
INSERT INTO sss_sistemas VALUES('SFP','Sistema de Formulación Presupuestaria');
INSERT INTO sss_sistemas VALUES('SIV','Sistema de Inventario');
INSERT INTO sss_sistemas VALUES('SNO','Sistema de Nomina');
INSERT INTO sss_sistemas VALUES('SNR','Sistema de Nomina Recursos Humano');
INSERT INTO sss_sistemas VALUES('SOB','Sistema de Obras');
INSERT INTO sss_sistemas VALUES('SOC','Sistema de Ordenes de Compra');
INSERT INTO sss_sistemas VALUES('SPG','Sistema de Gasto');
INSERT INTO sss_sistemas VALUES('SPI','Sistema de Ingresos');
INSERT INTO sss_sistemas VALUES('SRH','Recursos Humanos');
INSERT INTO sss_sistemas VALUES('SSS','Sistema de Seguridad');
