/********************************************************
 *SCRIPT BORRADO DE DOCUMENTOS TRANSFERIDOS ERRONEAMENTE*
 *CUENTAS X PAGAR					*
 ********************************************************/

/*
CADA SOLICITUD DE PAGO REALIZADA A NIVEL DE SISTEMA POSEE ATADA UNA RECEPCION DE DOCUMENTO (RD) DONDE 
SE REGISTRA LA AFECTACION CONTABLE Y PRESUPUESTARIA(SEGUN LO AMERITE LOS CASOS) DE DICHO PAGO. MUCHAS VECES
HA OCURRIDO QUE EL USUARIO DE MANERA ERRONEA TRANSFIERE UN DOCUMENTO DE UNA BASE DE DATO A OTRA (E INCLUSO A VECES LA MISMA).
POR ENDE PARA SOLVENTAR EL PROBLEMA, PRIMERAMENTE EL USUARIO DEBE INDICAR CUALES SON LOS NUMEROS DE DOCUMENTOS TRANSFERIDOS Y LUEGO SE PROCEDE A
REALIZAR LOS SIGUIENTES PASOS EN LA BASE DE DATOS EN LA CUAL SE ENCUENTRAN LAS SOLICITUDES DE PAGO ERRONEAS:


1)BORRAR A NIVEL PRESUPUESTARIO Y CONTABLE LAS RECEPCIONES DE DOCUMENTOS.
2)BORRAR LA RECEPCION DE DOCUMENTO A NIVEL DE CABECERA.
3)BORRAR LA SOLICITUD DE PAGO A DETALLE Y LUEGO LA CABECERA.

EL SIGUIENTE PASO SE REALIZA EN LA BASE DE DATOS ORIGEN(DONDE ESTABAN LAS SOLICITUDES DE PAGO ORIGINALMENTE)

4)ACTUALIZAR A EL VALOR 0(CERO) EL CAMPO ESTASOLPAG DE LA CABECERA DE LAS SOLICITUDES DE PAGOS (PARA QUE PUEDAN SER VISTAS NUEVAMENTE PARA SER TRANSFERIDAS).

*/

--1)BORRAR A NIVEL PRESUPUESTARIO Y CONTABLE LAS RECEPCIONES DE DOCUMENTOS.

--IDENTIFICAMOS LAS RECEPCIONES DE DOCUMENTOS CONTABLES DE LA SOLICITUD DE PAGO
SELECT T2.NUMRECDOC
FROM CXP_DT_SOLICITUDES T1
INNER JOIN CXP_RD_SCG T2 ON T1.NUMRECDOC=T2.NUMRECDOC
WHERE
T1.NUMSOL like '%10977%' 

--BORRAMOS LA RECEPCION
DELETE FROM CXP_RD_SCG WHERE NUMRECDOC=' 2348'


--IDENTIFICAMOS LAS RECEPCIONES DE DOCUMENTOS PRESUPUESTARIOS DE LA SOLICITUD DE PAGO
SELECT T2.NUMRECDOC
FROM CXP_DT_SOLICITUDES T1
INNER JOIN CXP_RD_SPG T2 ON T1.NUMRECDOC=T2.NUMRECDOC
WHERE
T1.NUMSOL like '%10977%' 

--BORRAMOS LA RECEPCION
DELETE FROM CXP_RD_SPG WHERE NUMRECDOC=' 2348'


--2)BORRAR LA RECEPCION DE DOCUMENTO A NIVEL DE CABECERA.

DELETE FROM CXP_RD WHERE NUMRECDOC=' 2348'

--3)BORRAR LA SOLICITUD DE PAGO A DETALLE Y LUEGO LA CABECERA.
--DETALLE
DELETE FROM CXP_DT_SOLICITUDES WHERE NUMSOL LIKE '%0010977%'
--CABECERA
DELETE FROM CXP_SOLICITUDES WHERE NUMSOL LIKE '%0010977%'


/*
EL SIGUIENTE PASO SE REALIZA EN LA BASE DE DATOS ORIGEN(DONDE ESTABAN LAS SOLICITUDES DE PAGO ORIGINALMENTE)

4)ACTUALIZAR A EL VALOR 0(CERO) EL CAMPO ESTASOLPAG DE LA CABECERA DE LAS SOLICITUDES DE PAGOS (PARA QUE PUEDAN SER VISTAS NUEVAMENTE PARA SER TRANSFERIDAS).

*/
UPDATE cxp_solicitudes 
SET estapesolpag='0' WHERE 
(numsol like '%0010977%') 

