INSERT INTO sno_nomina
SELECT 
	*
FROM 
	dblink('dbname=db_mdo_2015', 
	'SELECT 
		codemp,
		codnom,
		desnom,
		tippernom,
		despernom,
		anocurnom,
		fecininom,
		peractnom,
		numpernom,
		tipnom,
		subnom,
		racnom,
		adenom,
		espnom,
		ctnom,
		ctmetnom,
		diabonvacnom,
		diareivacnom,
		diainivacnom,
		diatopvacnom,
		diaincvacnom,
		consulnom,
		descomnom,
		codpronom,
		codbennom,
		conaponom,
		cueconnom,
		notdebnom,
		numvounom,
		recdocnom,
		tipdocnom,
		recdocapo,
		tipdocapo,
		perresnom,
		conpernom,
		conpronom,
		titrepnom,
		codorgcestic,
		confidnom,
		recdocfid,
		tipdocfid,
		codbenfid,
		cueconfid,
		informa,
		divcon,
		recdocpagperche,
		tipdocpagperche,
		estctaalt,
		racobrnom,
		nomliq,
		hojtienom,
		cestiksuel
	FROM 
		sno_nomina') 
	AS 
		sno_nomina(
			  codemp character(4),
			  codnom character(4),
			  desnom character varying(100),
			  tippernom character varying(1), 
			  despernom character varying(20),
			  anocurnom character(4),
			  fecininom date,
			  peractnom character(3),
			  numpernom integer,
			  tipnom smallint,
			  subnom character varying(1),
			  racnom character varying(1),
			  adenom character varying(1),
			  espnom character varying(1),
			  ctnom character varying(1),
			  ctmetnom character varying(2),
			  diabonvacnom integer,
			  diareivacnom integer,
			  diainivacnom integer,
			  diatopvacnom integer,
			  diaincvacnom integer,
			  consulnom character varying(50),
			  descomnom character varying(1),
			  codpronom character varying(10),
			  codbennom character varying(10),
			  conaponom character varying(50),
			  cueconnom character varying(25),
			  notdebnom character varying(1), 
			  numvounom character varying(1),
			  recdocnom character varying(1), 
			  tipdocnom character varying(5),
			  recdocapo character varying(1),
			  tipdocapo character varying(5),
			  perresnom character varying(3),
			  conpernom character varying(1),
			  conpronom character varying(1),
			  titrepnom character varying(50),
			  codorgcestic character varying(10),
			  confidnom character varying(5),
			  recdocfid character varying(1),
			  tipdocfid character varying(5),
			  codbenfid character varying(10),
			  cueconfid character varying(25),
			  informa text,
			  divcon character(1),
			  recdocpagperche character(1),
			  tipdocpagperche character varying(5),
			  estctaalt character(1),
			  racobrnom character varying(1),
			  nomliq character varying(1),
			  hojtienom character varying(1),
			  cestiksuel character varying(1));